version: "3.9"

services:
  api:
    container_name: influx_api
    restart: unless-stopped
    working_dir: /var/www/api
    volumes:
      - ./.:/var/www/api
      - ./.docker:/usr/local/etc/php/php.ini
    build:
      context: ./.docker/php/api
      args:
        user: developer
        uid: 1000
    depends_on:
      - nginx
      - mongo
      - redis
    networks:
      - backend

  nginx:
    image: nginx:alpine
    container_name: influx_nginx
    restart: unless-stopped
    ports:
      - "8000:8000" # rest-api
    volumes:
      - ./.:/var/www/api
      - ./.docker/nginx/sites-available:/etc/nginx/sites-available
      - ./.docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - backend

  redis:
    image: redis:latest
    container_name: influx_redis
    restart: always
    command: redis-server --requirepass root
    ports:
      - "6379:6379"
    networks:
      - backend

  mongo:
    image: mongo:latest
    container_name: influx_mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - '27017:27017'
    networks:
      - backend

  elasticsearch:
    image: elasticsearch:8.10.2
    container_name: influx_elasticsearch
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.zen.minimum_master_nodes=2
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elasticdata:/usr/share/elasticsearch/data
    ports:
      - '9200:9200'
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  elasticdata:
    driver: local
  database:
    driver: local